version: '3.9'
services:
  tagspaces-web:
    container_name: tagspaces-web
    build:
      context: ../
      dockerfile: ./Dockerfile
    image: tagspaces-web:latest
    ports:
      - '8080:80'
    volumes:
      - ./config/extconfig.js:/usr/share/nginx/html/extconfig.js
    depends_on:
      - s3server
    networks:
      deployment:
        ipv4_address: 172.173.100.1
  createbucket:
    container_name: createbucket
    build:
      context: ./createbucket
      dockerfile: ./Dockerfile
    image: createbucket:latest
    environment:
      - ACCESS_KEY_ID=accessKey1
      - SECRET_ACCESS_KEY=verySecretKey1
      - ENDPOINT=http://172.173.100.2:8000
      - BUCKET_NAME=testbucket
    depends_on:
      - s3server
    networks:
      deployment:
        ipv4_address: 172.173.100.5
  s3server:
    hostname: s3server-ts
    container_name: s3server
    image: zenko/cloudserver:latest-0.0.0
    restart: unless-stopped
    ports:
      - '8000:8000'
    volumes:
      - s3data:/usr/src/app/localData
      - s3metadata:/usr/src/app/localMetadata
      - ./cloudserver/authdata.json:/usr/src/app/conf/authdata.json
    environment:
      S3BACKEND: file
      # REMOTE_MANAGEMENT_DISABLE: 1
      LOG_LEVEL: debug
      SSL: 'false'
      # LISTEN_ADDR: 0.0.0.0
    networks:
      deployment:
        ipv4_address: 172.173.100.2

  s3manager:
    container_name: s3manger
    image: mastertinner/s3manager
    ports:
      - 8081:8081
    environment:
      - PORT=8081
      - ENDPOINT=172.173.100.2:8000
      - ACCESS_KEY_ID=accessKey1
      - SECRET_ACCESS_KEY=verySecretKey1
      - USE_SSL=false
    depends_on:
      - s3server
    networks:
      deployment:
        ipv4_address: 172.173.100.3
volumes:
  s3data:
  s3metadata:
networks:
  deployment:
    driver: bridge
    internal: false
    ipam:
      driver: default
      config:
        - subnet: 172.173.0.0/16
