name: Nightly E2E Tests Web Minio MacOS
on:
  schedule:
    - cron: '0 5 * * *'

jobs:
  e2eTestsWebMac:
    name: Test Web App MacOS
    runs-on: macos-latest
    steps:
      - name: Checking out default branch
        uses: actions/checkout@v2
        with:
          ref: develop
          submodules: true
      - name: Checkout TagspacesPro
        uses: actions/checkout@v2
        with:
          repository: tagspaces/tagspacespro
          token: ${{ secrets.CHECKOUT_TSPRO  }}
          path: extensions/tagspacespro
      - name: Checkout TestData
        uses: actions/checkout@v2
        with:
          repository: tagspaces/testdata
          path: tests/testdata
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: Running yarn install, prettier and type checks
        run: |
          yarn install --check-files --cache-folder .ycache
          yarn prettier-check
          yarn type-check
      - name: Run Unit tests
        run: yarn test-unit
      - uses: suisei-cn/actions-download-file@v1
        id: minio
        name: Download the Minio
        with:
          url: 'https://dl.min.io/server/minio/release/darwin-amd64/minio'
          target: tests/bin/
      - name: Make the Minio executable
        run: chmod +x ./tests/bin/minio
      - name: Run Electron tests
        run: |
          yarn install-ext
          yarn build-main
          yarn build-e2e
          yarn test-playwright-web-headless
      - uses: IgnusG/jest-report-action@v2.3.3
        if: always() # Run regardless of whether other steps failed
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          check-name: Report Web App Windows
          working-directory: tests
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-artifacts
          path: |
            tests/test-pages/
            tests/test-reports/
