name: Nightly E2E Tests Electon MacOS
on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  e2eTestsElectronMac:
    name: Test Desktop App Mac
    runs-on: macos-latest
    steps:
      - name: Checking out default branch
        uses: actions/checkout@v2
        with:
          ref: develop
          submodules: true
      - name: Checkout TestData
        uses: actions/checkout@v2
        with:
          repository: tagspaces/testdata
          path: tests/testdata
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Running yarn install, prettier and type checks
        run: |
          yarn install --check-files --cache-folder .ycache
          yarn prettier-check
          yarn type-check
      - name: Run Unit tests
        run: yarn test-unit
      - name: Run Electron tests
        run: |
          yarn install-ext-node
          yarn build-main
          yarn build-e2e
          yarn test-playwright
      - uses: IgnusG/jest-report-action@v2.3.3
        if: always() # Run regardless of whether other steps failed
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          check-name: Report Desktop App Windows
          working-directory: tests
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-artifacts
          path: |
            tests/test-pages/
            tests/test-reports/
