name: Nightly E2E Tests Web Minio macOS
on:
  schedule:
    - cron: '0 5 * * *'

jobs:
  e2eTestsWebMac:
    name: Test Web App MacOS
    runs-on: macos-latest
    steps:
      - name: Checking out default branch
        uses: actions/checkout@v2
        with:
          ref: develop
          submodules: true
      - name: Checkout TagspacesPro
        uses: actions/checkout@v2
        with:
          repository: tagspaces/tagspacespro
          token: ${{ secrets.CHECKOUT_TSPRO  }}
          path: extensions/tagspacespro
      - name: Checkout TestData
        uses: actions/checkout@v2
        with:
          repository: tagspaces/testdata
          path: tests/testdata
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Running npm install, prettier and type checks
        run: |
          npm install
          npm run prepare-web-pro
          npm run prettier-check
          npm run type-check
      - name: Run Unit tests
        run: npm run test-unit
      - uses: suisei-cn/actions-download-file@v1
        id: minio
        name: Download the Minio
        with:
          url: 'https://dl.min.io/server/minio/release/darwin-amd64/minio'
          target: tests/bin/
      - name: Make the Minio executable
        run: chmod +x ./tests/bin/minio
      - name: Run Electron tests
        run: |
          npm run build-e2e-web
          npm run test-playwright-web-headless
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-artifacts
          path: |
            tests/test-pages/
            tests/test-reports/
